export interface CurrencyInfo {
  code: string
  symbol: string
  name: string
  decimals: number
}

export const CURRENCIES: CurrencyInfo[] = [
  // ── 常用货币 ──
  { code: 'CNY', symbol: '¥', name: '人民币', decimals: 2 },
  { code: 'USD', symbol: '$', name: '美元', decimals: 2 },
  { code: 'EUR', symbol: '€', name: '欧元', decimals: 2 },
  { code: 'JPY', symbol: '¥', name: '日元', decimals: 0 },
  { code: 'GBP', symbol: '£', name: '英镑', decimals: 2 },
  { code: 'KRW', symbol: '₩', name: '韩元', decimals: 0 },
  { code: 'HKD', symbol: 'HK$', name: '港币', decimals: 2 },
  { code: 'TWD', symbol: 'NT$', name: '新台币', decimals: 2 },
  { code: 'SGD', symbol: 'S$', name: '新加坡元', decimals: 2 },
  { code: 'AUD', symbol: 'A$', name: '澳元', decimals: 2 },
  { code: 'CAD', symbol: 'C$', name: '加元', decimals: 2 },
  { code: 'CHF', symbol: 'CHF', name: '瑞士法郎', decimals: 2 },
  { code: 'THB', symbol: '฿', name: '泰铢', decimals: 2 },
  { code: 'NZD', symbol: 'NZ$', name: '新西兰元', decimals: 2 },
  // ── 亚洲 ──
  { code: 'INR', symbol: '₹', name: '印度卢比', decimals: 2 },
  { code: 'IDR', symbol: 'Rp', name: '印尼盾', decimals: 0 },
  { code: 'MYR', symbol: 'RM', name: '马来西亚林吉特', decimals: 2 },
  { code: 'PHP', symbol: '₱', name: '菲律宾比索', decimals: 2 },
  { code: 'VND', symbol: '₫', name: '越南盾', decimals: 0 },
  { code: 'KHR', symbol: '៛', name: '柬埔寨瑞尔', decimals: 2 },
  { code: 'LAK', symbol: '₭', name: '老挝基普', decimals: 0 },
  { code: 'MNT', symbol: '₮', name: '蒙古图格里克', decimals: 2 },
  { code: 'KPW', symbol: '₩', name: '朝鲜圆', decimals: 2 },
  { code: 'LKR', symbol: '₨', name: '斯里兰卡卢比', decimals: 2 },
  { code: 'NPR', symbol: '₨', name: '尼泊尔卢比', decimals: 2 },
  { code: 'PKR', symbol: '₨', name: '巴基斯坦卢比', decimals: 2 },
  { code: 'BND', symbol: '$', name: '文莱元', decimals: 2 },
  { code: 'KZT', symbol: 'лв', name: '哈萨克斯坦坚戈', decimals: 2 },
  { code: 'KGS', symbol: 'лв', name: '吉尔吉斯斯坦索姆', decimals: 2 },
  { code: 'UZS', symbol: 'лв', name: '乌兹别克斯坦苏姆', decimals: 2 },
  // ── 中东 ──
  { code: 'AED', symbol: 'د.إ', name: '阿联酋迪拉姆', decimals: 2 },
  { code: 'SAR', symbol: '﷼', name: '沙特里亚尔', decimals: 2 },
  { code: 'QAR', symbol: '﷼', name: '卡塔尔里亚尔', decimals: 2 },
  { code: 'OMR', symbol: '﷼', name: '阿曼里亚尔', decimals: 3 },
  { code: 'ILS', symbol: '₪', name: '以色列新谢克尔', decimals: 2 },
  { code: 'IRR', symbol: '﷼', name: '伊朗里亚尔', decimals: 0 },
  { code: 'LBP', symbol: '£', name: '黎巴嫩镑', decimals: 2 },
  { code: 'SYP', symbol: '£', name: '叙利亚镑', decimals: 2 },
  { code: 'YER', symbol: '﷼', name: '也门里亚尔', decimals: 2 },
  // ── 欧洲（非欧元区） ──
  { code: 'RUB', symbol: '₽', name: '俄罗斯卢布', decimals: 2 },
  { code: 'TRY', symbol: '₺', name: '土耳其里拉', decimals: 2 },
  { code: 'PLN', symbol: 'zł', name: '波兰兹罗提', decimals: 2 },
  { code: 'CZK', symbol: 'Kč', name: '捷克克朗', decimals: 2 },
  { code: 'HUF', symbol: 'Ft', name: '匈牙利福林', decimals: 0 },
  { code: 'SEK', symbol: 'kr', name: '瑞典克朗', decimals: 2 },
  { code: 'NOK', symbol: 'kr', name: '挪威克朗', decimals: 2 },
  { code: 'DKK', symbol: 'kr', name: '丹麦克朗', decimals: 2 },
  { code: 'ISK', symbol: 'kr', name: '冰岛克朗', decimals: 0 },
  { code: 'RON', symbol: 'lei', name: '罗马尼亚列伊', decimals: 2 },
  { code: 'BGN', symbol: 'лв', name: '保加利亚列弗', decimals: 2 },
  { code: 'HRK', symbol: 'kn', name: '克罗地亚库纳', decimals: 2 },
  { code: 'RSD', symbol: 'Дін.', name: '塞尔维亚第纳尔', decimals: 2 },
  { code: 'BAM', symbol: 'KM', name: '波黑可兑换马克', decimals: 2 },
  { code: 'MKD', symbol: 'ден', name: '北马其顿第纳尔', decimals: 2 },
  { code: 'ALL', symbol: 'Lek', name: '阿尔巴尼亚列克', decimals: 2 },
  { code: 'UAH', symbol: '₴', name: '乌克兰格里夫纳', decimals: 2 },
  { code: 'BYN', symbol: 'Br', name: '白俄罗斯卢布', decimals: 2 },
  { code: 'GGP', symbol: '£', name: '根西岛镑', decimals: 2 },
  { code: 'JEP', symbol: '£', name: '泽西岛镑', decimals: 2 },
  { code: 'IMP', symbol: '£', name: '马恩岛镑', decimals: 2 },
  { code: 'GIP', symbol: '£', name: '直布罗陀镑', decimals: 2 },
  { code: 'FKP', symbol: '£', name: '福克兰群岛镑', decimals: 2 },
  { code: 'SHP', symbol: '£', name: '圣赫勒拿镑', decimals: 2 },
  // ── 美洲 ──
  { code: 'BRL', symbol: 'R$', name: '巴西雷亚尔', decimals: 2 },
  { code: 'MXN', symbol: 'MX$', name: '墨西哥比索', decimals: 2 },
  { code: 'ARS', symbol: '$', name: '阿根廷比索', decimals: 2 },
  { code: 'CLP', symbol: '$', name: '智利比索', decimals: 0 },
  { code: 'COP', symbol: '$', name: '哥伦比亚比索', decimals: 2 },
  { code: 'PEN', symbol: 'S/.', name: '秘鲁索尔', decimals: 2 },
  { code: 'UYU', symbol: '$U', name: '乌拉圭比索', decimals: 2 },
  { code: 'PYG', symbol: 'Gs', name: '巴拉圭瓜拉尼', decimals: 0 },
  { code: 'BOB', symbol: '$b', name: '玻利维亚诺', decimals: 2 },
  { code: 'VEF', symbol: 'Bs', name: '委内瑞拉玻利瓦尔', decimals: 2 },
  { code: 'CRC', symbol: '₡', name: '哥斯达黎加科朗', decimals: 2 },
  { code: 'GTQ', symbol: 'Q', name: '危地马拉格查尔', decimals: 2 },
  { code: 'HNL', symbol: 'L', name: '洪都拉斯伦皮拉', decimals: 2 },
  { code: 'NIO', symbol: 'C$', name: '尼加拉瓜科多巴', decimals: 2 },
  { code: 'PAB', symbol: 'B/.', name: '巴拿马巴波亚', decimals: 2 },
  { code: 'DOP', symbol: 'RD$', name: '多米尼加比索', decimals: 2 },
  { code: 'CUP', symbol: '₱', name: '古巴比索', decimals: 2 },
  { code: 'JMD', symbol: 'J$', name: '牙买加元', decimals: 2 },
  { code: 'TTD', symbol: 'TT$', name: '特立尼达和多巴哥元', decimals: 2 },
  { code: 'BBD', symbol: '$', name: '巴巴多斯元', decimals: 2 },
  { code: 'BSD', symbol: '$', name: '巴哈马元', decimals: 2 },
  { code: 'BZD', symbol: 'BZ$', name: '伯利兹元', decimals: 2 },
  { code: 'BMD', symbol: '$', name: '百慕大元', decimals: 2 },
  { code: 'KYD', symbol: '$', name: '开曼群岛元', decimals: 2 },
  { code: 'XCD', symbol: '$', name: '东加勒比元', decimals: 2 },
  { code: 'AWG', symbol: 'ƒ', name: '阿鲁巴弗罗林', decimals: 2 },
  { code: 'ANG', symbol: 'ƒ', name: '荷属安的列斯盾', decimals: 2 },
  { code: 'SRD', symbol: '$', name: '苏里南元', decimals: 2 },
  { code: 'GYD', symbol: '$', name: '圭亚那元', decimals: 2 },
  { code: 'SVC', symbol: '$', name: '萨尔瓦多科朗', decimals: 2 },
  // ── 非洲 ──
  { code: 'ZAR', symbol: 'R', name: '南非兰特', decimals: 2 },
  { code: 'EGP', symbol: '£', name: '埃及镑', decimals: 2 },
  { code: 'NGN', symbol: '₦', name: '尼日利亚奈拉', decimals: 2 },
  { code: 'GHS', symbol: '¢', name: '加纳塞地', decimals: 2 },
  { code: 'NAD', symbol: '$', name: '纳米比亚元', decimals: 2 },
  { code: 'MUR', symbol: '₨', name: '毛里求斯卢比', decimals: 2 },
  { code: 'SCR', symbol: '₨', name: '塞舌尔卢比', decimals: 2 },
  { code: 'MZN', symbol: 'MT', name: '莫桑比克梅蒂卡尔', decimals: 2 },
  { code: 'BWP', symbol: 'P', name: '博茨瓦纳普拉', decimals: 2 },
  { code: 'LRD', symbol: '$', name: '利比里亚元', decimals: 2 },
  { code: 'SOS', symbol: 'S', name: '索马里先令', decimals: 2 },
  { code: 'ZWD', symbol: 'Z$', name: '津巴布韦元', decimals: 2 },
  // ── 大洋洲 ──
  { code: 'FJD', symbol: '$', name: '斐济元', decimals: 2 },
  { code: 'SBD', symbol: '$', name: '所罗门群岛元', decimals: 2 },
  { code: 'TVD', symbol: '$', name: '图瓦卢元', decimals: 2 },
  // ── 其他 ──
  { code: 'AFN', symbol: '؋', name: '阿富汗尼', decimals: 2 },
  { code: 'AZN', symbol: '₼', name: '阿塞拜疆马纳特', decimals: 2 },
]
